DROP TABLE wm_news_gallery;
DROP TABLE wm_news;

DROP TABLE wm_users;

DROP TABLE wm_user_role;
DROP TABLE wm_user_status;

DROP TABLE wm_communes;
DROP TABLE wm_provinces;
DROP TABLE wm_regions;

CREATE TABLE IF NOT EXISTS wm_regions (
  id_region INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  region VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE IF NOT EXISTS wm_provinces (
  id_province INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  province VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  region_id INTEGER NOT NULL,
  CONSTRAINT provinces_regions_fk FOREIGN KEY (region_id) REFERENCES wm_regions(id_region)
);

CREATE TABLE IF NOT EXISTS wm_communes (
  id_commune INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  commune VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  province_id INTEGER,
  CONSTRAINT communes_provinces_fk FOREIGN KEY (province_id) REFERENCES wm_provinces(id_province)
);

CREATE TABLE IF NOT EXISTS wm_user_status (
  id_user_status INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  status VARCHAR(45),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE IF NOT EXISTS wm_user_role (
  id_user_role INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  role VARCHAR(45) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wm_users (
  id_user UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(100),
  name VARCHAR(45),
  lastname VARCHAR(45),
  rut VARCHAR(12),
  address VARCHAR(256),
  phone VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  commune_id INTEGER,
  user_role_id INTEGER NOT NULL,
  user_status_id INTEGER NOT NULL,
  CONSTRAINT users_commune_fk FOREIGN KEY (commune_id) REFERENCES wm_communes(id_commune),
  CONSTRAINT users_types_fk FOREIGN KEY (user_role_id) REFERENCES wm_user_role(id_user_role),
  CONSTRAINT users_status_fk FOREIGN KEY (user_status_id) REFERENCES wm_user_status(id_user_status)
);

CREATE TABLE IF NOT EXISTS wm_news (
  id_news INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (INCREMENT 1),
  title VARCHAR(100) NOT NULL,
  subtitle VARCHAR(256) NOT NULL,
  body TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wm_news_gallery (
  id_news_gallery INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (INCREMENT 1),
  alt VARCHAR(100) NOT NULL,
  url VARCHAR(256) NOT NULL,
  news_id INTEGER,
  CONSTRAINT news_gallery_fk FOREIGN KEY (news_id) REFERENCES wm_news(id_news)
);

CREATE TABLE IF NOT EXISTS wm_editorials (
  id_editorial INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  editorial VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wm_authors (
  id_author INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO wm_regions (region) VALUES
('Región de Arica y Parinacota'),
('Región de Tarapacá'),
('Región de Antofagasta'),
('Región de Atacama'),
('Región de Coquimbo'),
('Región de Valparaíso'),
('Región Metropolitana de Santiago'),
('Región del Libertador General Bernardo O''Higgins'),
('Región del Maule'),
('Región de Ñuble'),
('Región del Biobío'),
('Región de La Araucanía'),
('Región de Los Ríos'),
('Región de Los Lagos'),
('Región de Aysén del General Carlos Ibáñez del Campo'),
('Región de Magallanes y de la Antártica Chilena');

INSERT INTO wm_provinces (province, region_id) VALUES
('Arica', 1),
('Parinacota', 1),
('Iquique', 2),
('Tamarugal', 2),
('Antofagasta', 3),
('El Loa', 3),
('Tocopilla', 3),
('Chañaral', 4),
('Copiapó', 4),
('Huasco', 4),
('Elqui', 5),
('Limarí', 5),
('Choapa', 5),
('Valparaíso', 6),
('Isla de Pascua', 6),
('Los Andes', 6),
('Petorca', 6),
('San Antonio', 6),
('San Felipe de Aconcagua', 6),
('Quillota', 6),
('Marga Marga', 6),
('Santiago', 7),
('Cordillera', 7),
('Chacabuco', 7),
('Maipo', 7),
('Melipilla', 7),
('Talagante', 7),
('Cachapoal', 8),
('Cardenal Caro', 8),
('Colchagua', 8),
('Talca', 9),
('Curicó', 9),
('Linares', 9),
('Cauquenes', 9),
('Diguillín', 10),
('Itata', 10),
('Punilla', 10),
('Concepción', 11),
('Biobío', 11),
('Arauco', 11),
('Cautín', 12),
('Malleco', 12),
('Valdivia', 13),
('Ranco', 13),
('Llanquihue', 14),
('Chiloé', 14),
('Osorno', 14),
('Palena', 14),
('Coyhaique', 15),
('Aysén', 15),
('General Carrera', 15),
('Capitán Prat', 15),
('Magallanes', 16),
('Última Esperanza', 16),
('Tierra del Fuego', 16),
('Antártica Chilena', 16);

INSERT INTO wm_communes (commune, province_id) VALUES
('Arica', 1),
('Camarones', 2),
('Putre', 2),
('General Lagos', 2),
('Iquique', 3),
('Alto Hospicio', 3),
('Pozo Almonte', 4),
('Camiña', 4),
('Colchane', 4),
('Huara', 4),
('Pica', 4),
('Antofagasta', 5),
('Mejillones', 5),
('Sierra Gorda', 5),
('Taltal', 5),
('Calama', 6),
('Ollagüe', 6),
('San Pedro de Atacama', 6),
('Tocopilla', 7),
('María Elena', 7),
('Chañaral', 8),
('Diego de Almagro', 8),
('Copiapó', 9),
('Caldera', 9),
('Tierra Amarilla', 9),
('Vallenar', 10),
('Alto del Carmen', 10),
('Freirina', 10),
('Huasco', 10),
('La Serena', 11),
('Coquimbo', 11),
('Andacollo', 11),
('Vicuña', 11),
('Illapel', 12),
('Canela', 12),
('Los Vilos', 13),
('Salamanca', 13),
('Valparaíso', 14),
('Viña del Mar', 14),
('Isla de Pascua', 15),
('Los Andes', 16),
('San Esteban', 16),
('Petorca', 17),
('La Ligua', 17),
('San Antonio', 18),
('Cartagena', 18),
('San Felipe', 19),
('Putaendo', 19),
('Quillota', 20),
('La Calera', 20),
('Villa Alemana', 21),
('Limache', 21),
('Santiago', 22),
('Providencia', 22),
('Ñuñoa', 22),
('Puente Alto', 23),
('Pirque', 23),
('Colina', 24),
('Lampa', 24),
('San Bernardo', 25),
('Buin', 25),
('Melipilla', 26),
('Alhué', 26),
('Talagante', 27),
('Peñaflor', 27),
('Rancagua', 28),
('Machalí', 28),
('San Fernando', 30),
('Santa Cruz', 30),
('Pichilemu', 29),
('La Estrella', 29),
('Talca', 31),
('Maule', 31),
('Curicó', 32),
('Hualañé', 32),
('Linares', 33),
('San Javier', 33),
('Cauquenes', 34),
('Chanco', 34),
('Chillán', 35),
('Chillán Viejo', 35),
('Quirihue', 36),
('Cobquecura', 36),
('Pinto', 37),
('Concepción', 38),
('Talcahuano', 38),
('Hualpén', 38),
('Los Ángeles', 39),
('Mulchén', 39),
('Lebu', 40),
('Cañete', 40),
('Arauco', 40),
('Temuco', 41),
('Villarrica', 41),
('Loncoche', 41),
('Angol', 42),
('Renaico', 42),
('Collipulli', 42),
('Valdivia', 43),
('Corral', 43),
('La Unión', 44),
('Río Bueno', 44),
('Puerto Montt', 45),
('Puerto Varas', 45),
('Castro', 46),
('Ancud', 46),
('Osorno', 47),
('Purranque', 47),
('Chaitén', 48),
('Futaleufú', 48),
('Coyhaique', 49),
('Lago Verde', 49),
('Aysén', 50),
('Cisnes', 50),
('Chile Chico', 51),
('Río Ibáñez', 51),
('Tortel', 52),
('Punta Arenas', 53),
('Puerto Natales', 54),
('Porvenir', 55),
('Cabo de Hornos', 55),
('Antártica', 56);

INSERT INTO wm_user_status (status)
VALUES 
('Activo/a'),
('Deudor/a'),
('Bloqueado/a');

INSERT INTO wm_user_role (role)
VALUES 
('Super Admin'),
('Admin'),
('Lector');

INSERT INTO wm_news (title, subtitle, body) VALUES
('Assassin’s Creed Valhalla, aventura vikinga',
 'Explora Inglaterra como un vikingo',
 'Assassin’s Creed Valhalla transporta a los jugadores al siglo IX, donde encarnan a Eivor, un guerrero vikingo. Con un mundo abierto lleno de exploración, combates y decisiones que afectan la historia, el juego busca combinar acción y narrativa histórica para los fanáticos de la saga.'),

('Cyberpunk 2077 sigue evolucionando',
 'Night City recibe mejoras y nuevas historias',
 'Cyberpunk 2077 ha logrado reinventarse tras su lanzamiento inicial, ofreciendo una experiencia más pulida y profunda en la icónica Night City. Con gráficos mejorados, misiones ampliadas y correcciones de bugs, los jugadores pueden sumergirse en un mundo futurista lleno de intrigas, tecnología avanzada y decisiones que afectan la historia. Cada actualización refuerza la narrativa y la libertad de exploración, manteniendo a Cyberpunk como un referente del RPG de mundo abierto en un entorno distópico y vibrante.'),

('Horizon continúa su aventura épica',
 'La saga de Aloy evoluciona con nuevos horizontes',
 'Horizon sigue cautivando a los jugadores con su mezcla de acción, exploración y narrativa envolvente. Con impresionantes paisajes y máquinas robóticas que desafían la imaginación, la saga ofrece una experiencia inmersiva única. Cada entrega expande la historia de Aloy, introduciendo nuevos territorios, enemigos y desafíos, manteniendo la esencia de aventura y descubrimiento que convirtió a Horizon en un referente de los RPG de mundo abierto modernos.'),

('Assassin’s Creed celebra su legado',
 'La franquicia que cambió los videojuegos de acción y aventuras',
 'La saga Assassin’s Creed, lanzada por primera vez en 2007, ha marcado un antes y un después en los videojuegos de mundo abierto. Con sus historias de conspiraciones históricas y exploración detallada de diferentes épocas, se ha ganado un lugar en el corazón de millones de jugadores alrededor del mundo. Cada entrega combina acción, sigilo y narrativa, manteniendo viva la esencia de la hermandad de asesinos a lo largo de los años.'),

('Oblivion regresa con Howard Legacy',
 'Una nueva versión que revitaliza el clásico RPG',
 'El remake Oblivion: HowardLegacy trae de vuelta la magia del clásico RPG de mundo abierto. Con gráficos actualizados y mejoras en la jugabilidad, los jugadores pueden explorar Tamriel con un nivel de detalle nunca antes visto. Esta versión conserva la narrativa rica y las misiones envolventes que hicieron famoso al título, ofreciendo tanto a fans antiguos como a nuevos jugadores la oportunidad de redescubrir la aventura épica en la tierra de los elfos, humanos y criaturas míticas.'),

('Hunter x Hunter sigue cautivando generaciones',
 'Aventuras, amistad, desafíos sin fin y el poder del NEN',
 'Hunter x Hunter es una saga que combina acción, estrategia y narrativa profunda, llevando a los espectadores a un mundo donde cazadores profesionales exploran territorios desconocidos y enfrentan desafíos únicos. Con personajes memorables, giros inesperados y una constante evolución de las habilidades de los protagonistas, la serie mantiene a los fans al borde del asiento. Cada arco amplía la historia, explorando la amistad, la ambición y los límites humanos, consolidando a Hunter x Hunter como un referente del anime moderno.'),

('Final Fantasy VII Remake: La épica historia regresa.',
 'La primera parte del remake revive el clásico de 1997 con gráficos impresionantes y un enfoque narrativo renovado.',
 'Square Enix ha vuelto a capturar la magia del icónico Final Fantasy VII con su remake, ofreciendo a los jugadores una experiencia completamente renovada mientras mantienen la esencia que hizo del original un clásico. La primera parte del remake se centra en la ciudad de Midgar, expandiendo la historia y los personajes con detalles y profundidad inéditos.

Los fans se maravillan con los gráficos modernos, el sistema de combate híbrido que mezcla acción y estrategia por turnos, y la banda sonora remasterizada que trae nostalgia y emoción. Aunque solo cubre la primera sección del juego original, los desarrolladores prometen que las siguientes partes continuarán con la misma fidelidad y expansión narrativa, manteniendo a los jugadores ansiosos por la próxima entrega.

Con un enfoque en la historia, los personajes y la jugabilidad, Final Fantasy VII Remake no solo rinde homenaje al título original, sino que también introduce el mundo a una nueva generación de jugadores, consolidándose como una de las experiencias RPG más destacadas de los últimos años.'),

('Elden Ring anuncia expansión sorpresa con nuevas regiones y jefes colosales.',
 'FromSoftware revela contenido inédito para Elden Ring que ampliará el mapa, incorporará desafiantes mazmorras y profundizará en el misterio de las Tierras Intermedias con nuevas líneas argumentales.',
 'Elden Ring vuelve a acaparar titulares tras el anuncio de una expansión sorpresa que promete ampliar significativamente la experiencia original. El estudio japonés FromSoftware confirmó que el nuevo contenido incluirá regiones completamente inéditas, enemigos nunca antes vistos y jefes de escala monumental que pondrán a prueba incluso a los jugadores más veteranos.

Según los primeros detalles, la expansión profundizará en el trasfondo de las Tierras Intermedias, explorando historias paralelas vinculadas al legado de los semidioses y a los fragmentos restantes del Círculo de Elden. También se introducirán nuevas armas, hechizos y mecánicas de combate que ampliarán las posibilidades de personalización.

Desde su lanzamiento en 2022, el título se consolidó como uno de los RPG de acción más influyentes de la década, gracias a su mundo abierto desafiante y su narrativa fragmentada. Con esta nueva expansión, el estudio busca revitalizar la comunidad y ofrecer retos aún más exigentes para quienes ya dominaron sus secretos.

La fecha de lanzamiento y el nombre oficial del contenido adicional se anunciarán próximamente, pero la expectativa entre los seguidores ya es enorme.'),

('Helldivers 2 recibe nueva ofensiva.',
 'Un parche masivo añade enemigos, armas y un bioma extremo para veteranos',
 'La guerra galáctica se intensifica. Helldivers 2 ha lanzado una actualización de gran magnitud que introduce una nueva ofensiva enemiga, poniendo a prueba incluso a los escuadrones más experimentados. El parche incluye una facción invasora con habilidades adaptativas que obligarán a los jugadores a replantear sus estrategias en el campo de batalla.

Entre las novedades destacan tres armas inéditas: un rifle de pulsos con daño en cadena, una escopeta incendiaria de corto alcance y un lanzador táctico capaz de desplegar cobertura portátil. Además, se han añadido estratagemas defensivas mejoradas, permitiendo solicitar drones de apoyo que patrullan zonas específicas durante tiempo limitado.

El nuevo bioma, un planeta volcánico azotado por tormentas electromagnéticas, añade peligros ambientales dinámicos. Erupciones repentinas, visibilidad reducida y fallos temporales en el equipamiento elevan la tensión en cada misión. La coordinación y la comunicación vuelven a ser claves para sobrevivir.

La comunidad ha reaccionado con entusiasmo ante el aumento de dificultad y la variedad de desafíos. Los desarrolladores han confirmado que este contenido forma parte de un plan de soporte continuo, con más eventos dinámicos y recompensas exclusivas programadas para las próximas semanas.

La Super Tierra necesita refuerzos. Y esta vez, la batalla será más brutal que nunca.'),

('La saga nórdica de God of War brilla',
 'Kratos y Atreus redefinen la acción en PS4 y PS5',
 'La saga nórdica de God of War y su secuela God of War Ragnarök marcó un antes y un después para la franquicia en PlayStation. Tras años centrada en la mitología griega, la serie reinventó su fórmula con una narrativa más madura, un combate renovado y un enfoque más íntimo en la relación entre Kratos y su hijo Atreus.

Lanzado originalmente en PS4, God of War (2018) sorprendió con su cámara en plano secuencia, su sistema de progresión RPG ligero y una exploración más abierta ambientada en los reinos de la mitología nórdica. El Leviatán, el hacha icónica de Kratos, se convirtió en símbolo de esta nueva etapa, combinando brutalidad y precisión táctica.

Por su parte, God of War Ragnarök elevó la apuesta en PS4 y especialmente en PS5, aprovechando la potencia de la nueva generación para ofrecer tiempos de carga casi inexistentes, combates más fluidos y una dirección artística aún más ambiciosa. La historia profundiza en el destino profetizado de Atreus y el inminente Ragnarök, enfrentando a los protagonistas a dioses como Thor y Odín.

La crítica y los jugadores coincidieron en destacar la evolución emocional de Kratos, ahora más humano y reflexivo, sin perder la intensidad que caracteriza a la saga. La etapa nórdica no solo revitalizó la franquicia, sino que consolidó a God of War como uno de los pilares narrativos y técnicos de PlayStation en la última década.'),

('Jedi Survivor expande la Fuerza.',
 'Cal Kestis regresa con combate más profundo y nuevos mundos.',
 'La galaxia vuelve a arder en Star Wars Jedi: Survivor, la esperada secuela de Star Wars Jedi: Fallen Order desarrollada por Respawn Entertainment. Ambientado cinco años después de los eventos anteriores, el título muestra a un Cal Kestis más experimentado, pero también más perseguido por el Imperio.

El nuevo capítulo amplía considerablemente los escenarios, ofreciendo planetas más abiertos, rutas opcionales y secretos que recompensan la exploración. El sistema de combate evoluciona con cinco posturas de sable de luz intercambiables, permitiendo adaptar el estilo de lucha a cada enfrentamiento, desde duelos rápidos hasta combates más pesados y estratégicos.

En PS5 y consolas de nueva generación, el juego destaca por su carga casi instantánea, mejoras gráficas y uso del control háptico para transmitir la intensidad de los choques de sable. Además, la narrativa profundiza en el conflicto interno de Cal, explorando temas como la resistencia, el sacrificio y el peso del legado Jedi.

Con una historia más oscura y ambiciosa, Jedi: Survivor consolida la saga como una de las adaptaciones más sólidas del universo Star Wars en videojuegos, combinando acción cinematográfica con exploración y desarrollo de personaje al más puro estilo Jedi.'),

('GTA V sigue dominando el mercado.',
 'El clásico de Rockstar mantiene su éxito en nueva generación.',
 'Más de una década después de su lanzamiento original, Grand Theft Auto V continúa siendo uno de los títulos más influyentes y vendidos de la industria. Desarrollado por Rockstar Games, el juego ha logrado mantenerse vigente gracias a constantes actualizaciones y su exitosa vertiente online.

En PS4 y PS5, GTA V ofrece mejoras visuales, mayor fluidez y tiempos de carga reducidos, especialmente en la versión optimizada para nueva generación. Los jugadores pueden elegir entre distintos modos gráficos que priorizan rendimiento o calidad visual, elevando la experiencia en la ciudad de Los Santos.

Por su parte, Grand Theft Auto Online sigue expandiéndose con nuevos golpes, vehículos, negocios y eventos semanales que mantienen activa a una comunidad masiva. Esta fórmula de contenido constante ha sido clave para que el juego continúe generando cifras récord año tras año.

Mientras la expectativa crece por el futuro de la franquicia, GTA V demuestra que su combinación de mundo abierto, narrativa criminal y libertad total sigue siendo una referencia dentro del género.');


INSERT INTO wm_news_gallery (alt, url, news_id) VALUES
('Eivor','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939914/news/uwe28f3sei5saumlfv7o.webp',1),
('Valhalla','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939915/news/u4ygl2bb6nql1y5xtsru.jpg',1),
('Eivor','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770941204/news/wuvh9nrza7ok9r1wclli.jpg',1),
('Valerie','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939716/news/jyhvpdp6qyfglg23dij0.webp',2),
('Vincent','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939718/news/t91p3kpx2cy1ypnkft0o.jpg',2),
('Cyberpunk 77','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939719/news/gcruoldoxvnvnoybmdlb.webp',2),
('Aloy','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770860243/news/ruatveggaye123paqwbv.webp',3),
('Aloy','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939388/news/f8bxmp98ctc5lfzr5yif.webp',3),
('Horizon','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939389/news/srveg87fsk5ybd8iiwz6.webp',3),
('Kassandra','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770935727/news/v9oxvx7lu7owst444k4h.jpg',4),
('Alexio','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939522/news/uozjmpr2yowenri4jfrs.webp',4),
('Odessy','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770939523/news/gujaxilkk854bws6vlon.jpg',4),
('Oblivion','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770936527/news/lendveswlwbuyeivubbj.webp',5),
('Hogwarts','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770936528/news/awlnzgejc6yhhmh6vxg5.webp',5),
('Oblivion','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770940063/news/rgrqye7kwl8lhdad9rfk.jpg',5),
('Gen''ei Ryodan','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770940393/news/yqoteucqnlwmdu3lt8dk.webp',6),
('Gon','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770940394/news/mfr18khtqxia0kica1co.webp',6),
('Killua','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1770940395/news/qg93qwmsovk2nphxb6nc.webp',6),
('Cloud Strife','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771257298/news/pgxw8jpjgiselqsuw4di.webp',7),
('Tifa Lockhart','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771257299/news/fg9pfhzxk287wvkok6c6.webp',7),
('Sephiroth','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771257300/news/pzkqszs9ysasdmysjayl.webp',7),
('Elden Ring','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771823372/news/nbsnfynpbawekafceblx.webp',8),
('Elden Ring','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771823372/news/driwxm2zqnpousc2rytc.webp',8),
('Elden Ring','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771823373/news/re10mxytego7w8bm0yzy.webp',8),
('Helldivers 2','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771885339/news/aa7ceeyz5v6bkbcqjowt.webp',9),
('Helldivers 2','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771885341/news/i9co1om3cc7tcn09abrc.webp',9),
('Helldivers 2','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771885342/news/pxvfuhf6webhyidlgigm.webp',9),
('Kratos','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771887680/news/gf83vsctlnzuupdsyrkt.webp',10),
('Ragnarok','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771887682/news/odoxyx9zpwkmaa66m7nk.webp',10),
('God Of War','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771951578/news/cijm92qqwa79xqqouwn9.webp',10),
('Jedi Survivor','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771888048/news/kpjxbetb7rze9j0jyu9m.webp',11),
('Jedi Survivor','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771888049/news/mgulzfkp4xvefmtysrn1.webp',11),
('Cal Kestis','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771888050/news/fuvvnesjs0jx8bdhw7zn.webp',11),
('GTA 5','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771888405/news/bmillgcolenf9kfwc7kv.webp',12),
('GTA 5','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771888406/news/bvzm5cwazjbyvdfriawq.webp',12),
('GTA 5','https://res.cloudinary.com/dsvkbe0mc/image/upload/v1771888407/news/lhjoz9ethysntixpm373.webp',12);


INSERT INTO wm_editorials (editorial) VALUES 
('Academia Chilena de la Lengua'),
('Alfaguara'),
('Ediciones Desidia'),
('Ediciones Occidente'),
('Ediciones Prosa'),
('Ediciones SM'),
('Edisur'),
('Editorial Andrés Bello'),
('Editorial Atlantida'),
('Editorial Bruño'),
('Editorial Don Bosco'),
('Editorial Ercilla'),
('Editorial Everest'),
('Editorial Grijalbo'),
('Editorial Maeva ediciones'),
('Editorial Planeta'),
('Editorial Planeta Chile'),
('Editorial Ramón Sopena'),
('Editorial Universitaria'),
('Editorial Vincens Vives'),
('Editorial Zig-Zag'),
('Grupo Editorial Planeta'),
('Javier Vergara Editor'),
('LOM Edición'),
('La Nación'),
('Maeva Ediciones'),
('Maeva Ediciones/Editorial Oceáno'),
('Penguin Random House'),
('Plaza Janés'),
('Publicaciones Lo Castillo'),
('Publicaciones y Ediciones Salamanca');


INSERT INTO wm_authors (author) VALUES
('AQUINO TOMAS DE'),
('Academia Chilena de la lengua'),
('Adler, David A.'),
('Agostini, Giorgio'),
('Ahlberg, Allan'),
('Aiken, Joan'),
('Alarcon, Pedro Antonio de'),
('Alcott Louisa M.'),
('Alcott, Louisa M.'),
('Alcántara Ricardo'),
('Aldunate P.Arturo'),
('Alegria Gloria'),
('Alegria fernando'),
('Alegria r. gloria'),
('Allamand maite'),
('Allende isabel'),
('Alliende, Felipe'),
('Alonso Manuel L.'),
('Alvarez Pablo/Marco Antonio …'),
('Amicis edmundo de'),
('Amira,baradit,flores y otros'),
('Ampuero roberto'),
('Anabalon alejandro'),
('Andersen H.C.'),
('Anderson rachel'),
('Andresen ute'),
('Aristofanes'),
('Aristoteles'),
('Armstrong william'),
('Auel jean'),
('Ayala ernesto'),
('Bach richard'),
('Bagge peter'),
('Balcells jacqueline'),
('Balcells jacqueline,guiraldes ana m.'),
('Balliett blue'),
('Balzac honorato de'),
('Balzola asun'),
('Banscherus jurgen'),
('Baquedano lucia'),
('Barbadillo patricia'),
('Barria jara mauricio'),
('Barrios eduardo'),
('Barrios enrique'),
('Bastias g. eduardo'),
('Baum franck'),
('Becquer gustavo A.'),
('Beecher enriqueta'),
('Belli Gioconda'),
('Beltran maria isabel'),
('Benton jim'),
('Bequer gustavo adolfo'),
('Bernal gonzalez patricia'),
('Bertrand sara'),
('Beuchat cecilia'),
('Birdsall jeanne'),
('Blanco guillermo'),
('Blasco ibañez vicente'),
('Blest gana alberto'),
('Bodoc liliana'),
('Bombal Maria Luisa'),
('Bombal maria luisa'),
('Borges jorge L.'),
('Bornemann elsa'),
('Boyd violeta'),
('Bradbury ray'),
('Brennan herbie'),
('Bresky A.'),
('Brezan jurij'),
('Brittney lynn'),
('Bronte carlota'),
('Bronzon M. B.'),
('Browne maria magdalena'),
('Bruckberger raymond L.'),
('Brunet marta'),
('Buck pearl S.'),
('Bukowski Charles'),
('Burnett frances hodgson'),
('Buroto pinto juan felix'),
('Burt michael'),
('Buzzati Dino'),
('Bydlinski georg'),
('Byng georgia'),
('Cabezas Esteban'),
('Calderon Patricia'),
('Calderon de la Barca Pedro'),
('Caldwell Taylor'),
('Calvo Mayo'),
('Cameron Ann'),
('Camus Albert'),
('Canihuante Maureira Gabriel'),
('Capo Jesus'),
('Carkovic Antonio'),
('Carrasco Jose Luis'),
('Carrasco M Eliana'),
('Carroll Lewis'),
('Carstens Carolina-Huepe Gabriela'),
('Carvajal Victor'),
('Casalderrey Fina'),
('Casona Alejandro'),
('Castro Oscar'),
('Caucao Jaime'),
('Cañizo Jose Antonio del'),
('Cela camilo jose'),
('Cermeño Xose'),
('Cervantes miguel de'),
('Chandelle Rene'),
('Chaucer Geoffrey'),
('Chavez Castañeda Ricardo'),
('Christie Agatha'),
('Ciceron'),
('Civico Irene-Parra Sergio'),
('Clare Cassandra'),
('Clavel Bernard'),
('Clavel James'),
('Coelho Paulo'),
('Collazos Oscar'),
('Collins Larry'),
('Collins Suzanne'),
('Collis Maurice'),
('Collodi Carlo'),
('Coloane Francisco'),
('Company Merce'),
('Condemarin Mabel'),
('Conrad Joseph'),
('Cooper Fenimore'),
('Corma Avery'),
('Corman Avery'),
('Correa Hugo'),
('Cortazar Julio'),
('Cosnava Javier-Del Rincon Ruben'),
('Costa Marco Tulio'),
('Crompton Richmal'),
('Cross Gillian'),
('Cuauhtemoc Sanchez Carlos'),
('Curwood James Oliver'),
('Dahl Michael'),
('Dahl Roald'),
('Dale Anna'),
('Danzinger Paula'),
('Dario Ruben'),
('Darwin Charles'),
('Dashner James'),
('Daudet Alfonso'),
('Daurevilly Barbey'),
('Davigneau Patricia Marie'),
('Davis Lindsey'),
('Deb Michel'),
('Debesa Fernando'),
('Defoe Daniel'),
('Delano Poli'),
('Descartes Rene'),
('Diaz Eterovic Ramon'),
('Diaz Jorge'),
('Dickens Charles'),
('Dickinson Peter'),
('Dieguez Violeta'),
('Doherty Berlie'),
('Donoso Jose'),
('Dos Passos John'),
('Dostoievski Fedor'),
('Doyle Arthur Conan'),
('Dros Imme'),
('Druon Maurice'),
('Dueñas Maria'),
('Dumas Alejandro'),
('Duprau Jeanne'),
('Durini Angeles'),
('Durrell Gerald'),
('Edwards Angelica'),
('Einstein Albert'),
('Ellis David'),
('Ende Michael'),
('Ercilla Alonso de'),
('Escudero Laura'),
('Escudie Rene'),
('Espino Jose Manuel'),
('Esquilo'),
('Esquivel Laura'),
('Estrada Rafael'),
('Falcones Ildefonso'),
('Falconi Maria Ines'),
('Fariña Soledad'),
('Fasmer Titt'),
('Fenieux Campos Alicia'),
('Fernandez de Moratin L'),
('Ferre Rosario'),
('Fine Anne'),
('Fisgon historico'),
('Fisher Robert'),
('Flaubert Gustavo'),
('Fleming Ian'),
('Florenzano Sergio'),
('Flores JL'),
('Follett Ken'),
('Fombelle Timothee'),
('Fonseca Cristina Da'),
('Fossa Rojas Aldo'),
('Foutz Virgil W'),
('Frabetti Carlo'),
('Frank Ana'),
('Frenkel Francoise'),
('Freud Sigmund'),
('Frewin Jones Allan'),
('Fuguet Alberto'),
('Funke Cornelia'),
('Gallego Garcia Laura'),
('Gallegos Garcia Laura'),
('Gallegos Manuel'),
('Gallegos Romulo'),
('Gamboa Alberto'),
('Garces Mario'),
('Garcia Barria Narciso'),
('Garcia Clairac Santiago'),
('Garcia Huidobro Beatriz'),
('Garcia Iglesias Carmen'),
('Garcia Lorca Federico'),
('Garcia Marquez Gabriel'),
('Gibran Kahlil'),
('Goethe Wolfgang'),
('Golding William'),
('Gomez Cerda Alfredo'),
('Gomez Sergio'),
('Gordon Noah'),
('Gorki Maximo'),
('Goscinny Rene'),
('Goudge Elizabeth'),
('Griffin Adele'),
('Grimm Jakob y Wilhelm'),
('Gripe Maria'),
('Grisham John'),
('Guajardo Marcelo'),
('Guattari Felix'),
('Gubbins Georgina'),
('Guiraldes Ana Maria'),
('Guiraldes Ricardo'),
('Guzman B., Rosario'),
('Guzman Nancy'),
('Haggard Rider H'),
('Harlon Abby'),
('Harris Thomas…'),
('Hartling Peter'),
('Harwicz Ariana'),
('Hauff Wilhelm'),
('Hay Louise'),
('Hayder Mo'),
('Hearn Lian'),
('Heaven Constance'),
('Heiremans Luis A.'),
('Hemingway Ernest'),
('Hernandez Vergara Lilia'),
('Herranz Sara'),
('Hertling Gisela'),
('Hesse Hermann'),
('Hidalgo Hector'),
('Hill Stuart'),
('Hilton James'),
('Hinojosa Francisco'),
('Hinton Susan'),
('Hirsh M. E.'),
('Hite Shere'),
('Hodgson Burnet Frances'),
('Holroyd Michael'),
('Homero'),
('Hornby Nick'),
('Horowitz Anthony'),
('Howker Janni'),
('Hubbard Susan'),
('Hugo Victor'),
('Huidobro Norma'),
('Huneeus Pablo'),
('Ibañez Magdalena'),
('Ibsen Henrik'),
('Iles Francis'),
('Inkiow Dimiter'),
('Ionescu Angela'),
('Iribarren Diaz Hector M.'),
('Isaacs Jorge'),
('James P.D.'),
('Jaume Ribera Andreau'),
('Jeftanovic Andrea'),
('Jimenez Juan Ramon'),
('Jimenez Juan Ramon-c1'),
('Johannes Stein Walter'),
('Jordan Jimenez Felipe'),
('Jouffe Andre'),
('Jurgensen Harry'),
('Kafka Franz'),
('Kaplan Robert D.'),
('Kemal Yasar'),
('Keselman Gabriela'),
('King Stephen'),
('Kipling Rudyard'),
('Kirkegaard Ole Lund'),
('Klein Sergio'),
('Kloepfer John'),
('Kordon Klaus'),
('Korschunow Irina'),
('Kosinski Jerzy'),
('Krantz Judith'),
('Kropp Paul'),
('Lackberg Camilla'),
('Ladronde Guevara Eliana'),
('Lagerlof Selma'),
('Lalana Fernando'),
('Lanzotti Paolo'),
('Larsson Stieg'),
('Lawrence Caroline'),
('Lawrence D.H.'),
('Lederer y Buraik'),
('Lemebel Pedro'),
('Leon Fray Luis de'),
('Lesage Alain Rene'),
('Lewis C.S.'),
('Leñero Carmen'),
('Liberona Concha Nanette'),
('Lienas Gemma'),
('Lillo Baldomero'),
('Lind Hera'),
('Livan Paco'),
('Lobe Mira'),
('London Jack'),
('Lope de Vega'),
('Lopez Narvaez Concha'),
('Loves June'),
('Lozano Garbala David'),
('Ludlum Robert'),
('Maalouf Amin'),
('Mac donald Megan'),
('Machado Ana Maria'),
('Machado Joaquim Maria'),
('Mahy Margaret'),
('Maitena'),
('Malley Gemma'),
('Malot Hector'),
('Mann Thomas'),
('Manrique Jorge'),
('Mansour Vivian'),
('Marcela Serrano'),
('Marcone Maria'),
('Margolin Phillip'),
('Marin German'),
('Mariño Ricardo'),
('Martin A/Ribera J'),
('Martin Kat'),
('Martinic Torrealba Ana Maria'),
('Masini Beatrice'),
('Mason Conrad'),
('Massimo Manfredi Valerio'),
('Masterton Graham'),
('Mateos Pilar'),
('Mathiw de jesus'),
('Maturana Andrea'),
('Maupassant Guy de'),
('Mc Caughrean Geraldine'),
('Mc donald Megan'),
('Mellado Marcelo'),
('Melville Herman'),
('Mendez Maria Luisa'),
('Mendez Mario'),
('Menendez Elvira-jose M Alvarez'),
('Menendez Maria-Ponte'),
('Mernissi Fatema'),
('Meyer Stephene'),
('Milicic Neva'),
('Miller Kirsten'),
('Minaya Nelson Julio'),
('Mistral Gabriela'),
('Mnacko Ladislav'),
('Molier'),
('Molina Alicia'),
('Molina Maria Isabel'),
('Molina Tirso'),
('Molina Tirso-Zorrilla Jose'),
('Molina tirso de'),
('Monteilhet H.'),
('Montenegro Ernesto'),
('Morabito Fabio'),
('Morel Alicia'),
('Moreno Jashes Alejandro'),
('Moreno Mario'),
('Morrison Pearl'),
('MoulianTomas'),
('Moyano Altamirano Cristian'),
('Muchamore Robert'),
('Munthe Axel'),
('Mutis Alvaro'),
('Muñoz Martin Juan'),
('Muñoz Puelles Vicente'),
('Neruda Pablo'),
('Neuschafer Mercedes'),
('Newton Isaac'),
('Nicholson William'),
('Nostlinger Christine'),
('Nuñez Duran Rodolfo'),
('OE Kenzaburgo'),
('Olaizola Jose Luis'),
('Olea Raquel'),
('Oliver Lauren'),
('Ortega Riquelme Miguel'),
('Ortega yGaset'),
('Orwell George'),
('Oses Beatriz'),
('Oses Dario'),
('Osman Ahmed'),
('Ouchi William'),
('Oz Amos'),
('Paine Michael'),
('Palma Javiera'),
('Palma Ricardo'),
('Palma Zarate Mauricio'),
('Pancol Katherine'),
('Paredes Mauricio'),
('Parra Nicanor'),
('Parra Roberto'),
('Pasternak Boris'),
('Paterson Katherine'),
('Paut de Elisa'),
('Paz Marcela'),
('Paz Marcela y Alicia Morel'),
('Paz Marcela/Alicia Morel'),
('Peet Mal'),
('Pelayo Pepe'),
('Pelayo Pepe/Betan'),
('Pereira Manuel/Fidel Sepulveda'),
('Perera Hilda'),
('Perez  Galdos Benito'),
('Perez Floridor'),
('Perez Galdos Benito'),
('Perez Rosales Vicente'),
('Pesce Franco'),
('Pescetti Luis Maria'),
('Petit Magdalena'),
('Pezoa Veliz Carlos'),
('Peña M.Manuel'),
('Pilkey Dav'),
('Piña Juan Andres'),
('Piñeiro Claudia'),
('Platon'),
('Plutarco'),
('Poe Edgar Allan'),
('Polo Marco'),
('Posadas Carmen de'),
('Prado Pedro'),
('Pulido Cifuentes  Rene'),
('Puncel Maria'),
('Queirolo Bravo Jorge'),
('Queiroz Jose Maria'),
('Quevedo Francisco de'),
('Quiller Couch'),
('Quiroga  Carlos'),
('Quiroga Horacio'),
('Rabelais Francois'),
('Radrigan Juan'),
('Reberg Eveline'),
('Reeve Philip'),
('Retti Christine'),
('Reyes Yolanda'),
('Riel jorn'),
('Rimington Stella'),
('Rio Ana Maria del'),
('Riordan Rick'),
('Riso Walter'),
('Rivera Jose Eustacio'),
('Rivera Letelier Hernan'),
('Roberts Nora'),
('Rodari Gianni'),
('Rodriguez Fisher Ana'),
('Rojas Juany'),
('Rojas Manuel'),
('Romana Muriel'),
('Ron-Feder Galila'),
('Rosasco Jose Luis'),
('Rostand Edmond'),
('Roth Veronica'),
('Rotterdam Erasmo de'),
('Rousseau Jean-Jacques'),
('Rowell Rainbow'),
('Rowling J.K.'),
('Ruedlinger Jorge G.'),
('Ruiz Arturo'),
('Ruiz Zafon Carlos'),
('Ruiz-Tagle Cralos'),
('Rulfo Juan'),
('Rus Rebeca'),
('Sabato Ernesto'),
('Sabbatino Marcela'),
('Saez Mariel'),
('Saint Laurent Cecil'),
('Saint-Exupery Antoine'),
('Salgari Emilio'),
('Sanchez Ibarzabal Paloma'),
('Sanchez Silva Jose Maria'),
('Santiago Roberto'),
('Santivan Fernando'),
('Santos Care'),
('Saramago Jose'),
('Saravia C. Felipe'),
('Savater Fernando'),
('Sawyer Robert'),
('Saylor Carol'),
('Schkolnik Saul'),
('Scott Paul'),
('Scott Walter'),
('Selznick Brian'),
('Sempe/Goscinny'),
('Sepulveda Fidel'),
('Sepulveda Luis'),
('Serrano Marcela'),
('Sewell Anna'),
('Shakespeare William'),
('Sharpe Susan'),
('Sheldon Sidney'),
('Sienkiewicz Enrique'),
('Sierra i Fabra Jordi'),
('Sieveking Alejandro'),
('Silva Hugo'),
('Silva Maria Luisa'),
('Silva Victor Domingo'),
('Simenon'),
('Simonetti Marcelo'),
('Simonetti Pablo'),
('Sinclair Upton'),
('Singer Isaac B.'),
('Skelton Matthew'),
('Sofocles'),
('Solar Hernan del'),
('Sommer Bodenburg Angela'),
('Sordo Pilar'),
('Soto Maria de la Luz'),
('Spiegeman'),
('St john Lauren'),
('Stark Ulf'),
('Steel Danielle'),
('Stendhal'),
('Stevenson Robert'),
('Stewart Mary'),
('Subercaseaux Benjamin'),
('Subercaseaux Elizabeth'),
('Swift Jonathan'),
('Swindells R.'),
('Tagore Rabindranath'),
('Tahan Malba'),
('Talbot Mary M.'),
('Teillier Jorge'),
('Teitelboim Volodia'),
('Teixidor Emili'),
('Tejeda Juan'),
('Terlouw Jan'),
('Tirado Maria Jose'),
('Tirapegui I.C.'),
('Toledo Navarro Ana'),
('Tolkien J.R.R.'),
('Tolstoi Leon'),
('Troyat Henri'),
('Twain Mark'),
('Unamuno Miguel de'),
('Uris Leon'),
('Valencak Hannelore'),
('Valenzuela Leon Camila'),
('Valenzuela Luisa'),
('Varela Nuria'),
('Vargas Llosa Mario'),
('Vargas Maria Eugenia'),
('Vasconcelos Jose Mauro de'),
('Vasilievich Gogol'),
('Vasquez Lagos Eduardo'),
('Vazquez-Vigo Carmen'),
('Vega Garcilaso de la'),
('Vega Lope de'),
('Velasco Francisco'),
('Ventura Antonio'),
('Vergara ehrenberg Carlos'),
('Verne Julio'),
('Vidal Cesar'),
('Vidal Virginia'),
('Viguera Martinez Daniel'),
('Vila-San-Juan'),
('Villoro Juan'),
('Visone Andrea Edoardo'),
('Voltaire'),
('Wallace Lewis'),
('Webb Beth'),
('Webster Jean'),
('Wells Herbert George'),
('West Morris'),
('Whitacre Haines'),
('Whitmore Ken'),
('Whitting George'),
('Wilde Oscar'),
('Wilson Eric'),
('Wiseman Cardenal'),
('Wolfel Ursula'),
('Wolff Egon'),
('Wood Barbara'),
('Woolf Virginia'),
('Yankas Lautaro'),
('Yañez Agustin'),
('Yañez Langer Marcelo'),
('Yo soy Malala'),
('Zorrilla Jose'),
('Zulma'),
('anonimo oriental'),
('antologia'),
('antolologia ilustrada');
